# 触发的事件
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: git Actions
        uses: srt32/git-actions@v0.0.3
      - name: Setup
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          ACTION_PUBLIC_KEY: ${{ secrets.ACTION_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$ACTION_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan 47.102.122.237 >> ~/.ssh/known_hosts
          git config --global user.email "1123598783@qq.com"
          git config --global user.name "boses"
          npm install
          npm run deploy
